services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    container_name: mini_app_db
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_app
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mini_app']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mini_app_network

volumes:
  db_data:
    driver: local

networks:
  mini_app_network:
    driver: bridge

